import { Italiana } from "next/font/google";
import "./globals.css";

const italiana = Italiana({
  variable: "--font-italiana",
  weight: '400',
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${italiana.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}